services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: pnpm install
    startCommand: cd packages/cli/bin && ./n8n
    nodeVersion: 18.18.0
    autoDeploy: true
